### ISSUE TITLE
Creating a Check doesn't work for foreign PRs

### ISSUE THREAD

**Issue by MeFisto94** [MeFisto94/spotbugs-github-integration#2]
```
(node:3767) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/test-spotbugs/test-spotbugs/bot/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/test-spotbugs/test-spotbugs/bot/index.js:157:17
(node:3767) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
Also we should catch that promises to be future proof.

https://github.com/MeFisto94/spotbugs-github-integration/blob/f42e660adad82add35f4329566b1f049e04d66fe/index.js#L157-L167

**Comment by MeFisto94** [comment]
The only solution I see is not running the code from within github actions, because for PRs we don't even have a safe way of adding a PAT.

Github doesn't want PRs modifying the CI to screw everything.
Is there a way to disable this behavior and just don't build when the workflows have been changed?

**Comment by MeFisto94** [comment]
This is probably the reason why I will discontinue this project in favor of a dedicated probot based bot, which actually does the _same_ without running through github actions.

It'll also cover more analysis in a central point (which would've been different github action runs and repositories otherwise).
